PhoneBook.Web/Controllers/PhoneBookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PhoneBook.Data.Entities;
using PhoneBook.Services.Services;
using PhoneBook.Web.Models.PhoneBookViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneBook.Web.Controllers
{
    public class PhoneBookController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IContactService _contactService;
        private readonly IContactInformationService _contactInformationService;
        private readonly IInformationTypeService _informationTypeService;

        public PhoneBookController(IConfiguration configuration, IContactService contactService, IContactInformationService contactInformationService, IInformationTypeService informationTypeService)
        {
            _configuration = configuration;
            _contactService = contactService;
            _contactInformationService = contactInformationService;
            _informationTypeService = informationTypeService;
        }

        // Information Type

        [HttpGet]
        public async Task<IActionResult> InformationTypeIndex()
        {
            var informationTypes = await _informationTypeService.GetInformationTypesAsync();
            return View(informationTypes);
        }

        [HttpGet]
        public IActionResult CreateInformationType()
        {
            var informationTypeModel = new InformationTypeCreateDto();
            return View(informationTypeModel);
        }
        [HttpPost]
        public async Task<IActionResult> CreateInformationType(InformationTypeCreateDto informationTypeModel)
        {
            var informationType = new InformationType
            {
                Name = informationTypeModel.Name
            };
            await _informationTypeService.AddInformationTypeAsync(informationType);
            return RedirectToAction(nameof(InformationTypeIndex));
        }

        [HttpGet]
        public async Task<IActionResult> EditInformationType(int informationTypeId)
        {
            var informationType = await _informationTypeService.GetInformationTypeAsync(informationTypeId);
            var informationTypeModel = new InformationTypeEditDto
            {
                UUID = informationType.UUID,
                Name = informationType.Name
            };
            return View(informationTypeModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditInformationType(InformationTypeEditDto informationTypeModel)
        {
            var informationType = await _informationTypeService.GetInformationTypeAsync(informationTypeModel.UUID);
            informationType.Name = informationTypeModel.Name;
            await _informationTypeService.UpdateInformationTypeAsync(informationType);
            return RedirectToAction(nameof(InformationTypeIndex));
        }

        public async Task<IActionResult> DeleteInformationType(int informationTypeId)
        {
            if ((await _contactInformationService.GetContactInformationsAsync()).Any(c => c.InformationTypeId == informationTypeId))
            {
                TempData["message"] = "Type related with contact informations!";
                return RedirectToAction(nameof(InformationTypeIndex));
            }
            await _informationTypeService.DeleteInformationTypeAsync(informationTypeId);
            return RedirectToAction(nameof(InformationTypeIndex));
        }

        // Contact

        [HttpGet]
        public async Task<IActionResult> ContactIndex()
        {
            var contacts = await _contactService.GetContactsAsync();
            return View(contacts);
        }

        [HttpGet]
        public async Task<IActionResult> ViewContact(int contactId)
        {
            var contact = await _contactService.GetContactWithContactInformationsAsync(contactId);
            var viewContactModel = new ViewContactDto
            {
                UUID = contact.UUID,
                Name = contact.Name,
                Surname = contact.Surname,
                Company = contact.Company,
                ContactInformations = contact.ContactInformations,
                InformationTypes = await _informationTypeService.GetInformationTypesAsync()
            };
            return View(viewContactModel);
        }

        [HttpGet]
        public IActionResult CreateContact()
        {
            var contactModel = new ContactCreateDto();
            return View(contactModel);
        }
        [HttpPost]
        public async Task<IActionResult> CreateContact(ContactCreateDto contactModel)
        {
            var contact = new Contact
            {
                Name = contactModel.Name,
                Surname = contactModel.Surname,
                Company = contactModel.Company
            };
            await _contactService.AddContactAsync(contact);
            return RedirectToAction(nameof(ContactIndex));
        }

        [HttpGet]
        public async Task<IActionResult> EditContact(int contactId)
        {
            var contact = await _contactService.GetContactAsync(contactId);
            var contactModel = new ContactEditDto
            {
                UUID = contact.UUID,
                Name = contact.Name,
                Surname = contact.Surname,
                Company = contact.Company
            };
            return View(contactModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditContact(ContactEditDto contactModel)
        {
            var contact = await _contactService.GetContactAsync(contactModel.UUID);
            contact.Name = contactModel.Name;
            contact.Surname = contactModel.Surname;
            contact.Company = contactModel.Company;
            await _contactService.UpdateContactAsync(contact);
            return RedirectToAction(nameof(ContactIndex));
        }

        public async Task<IActionResult> Deletecontact(int contactId)
        {
            await _contactService.DeleteContactAsync(contactId);
            return RedirectToAction(nameof(ContactIndex));
        }

        // Contact Information

        [HttpGet]
        public async Task<IActionResult> CreateContactInformation(int contactId)
        {
            var informationTypes = await _informationTypeService.GetInformationTypesAsync();
            if (informationTypes.Count() == 0)
            {
                TempData["message"] = "Add types before creating contact informations!";
                return RedirectToAction("ViewContact", new { contactId });
            }
            var contact = await _contactService.GetContactAsync(contactId);
            var contactInformationModel = new ContactInformationCreateDto
            {
                ContactId = contactId,
                ContactName = contact.Name + " " + contact.Surname,
                InformationTypes = informationTypes
            };
            return View(contactInformationModel);
        }
        [HttpPost]
        public async Task<IActionResult> CreateContactInformation(ContactInformationCreateDto contactInformationModel)
        {
            var contactInformation = new ContactInformation
            {
                ContactId = contactInformationModel.ContactId,
                Content = contactInformationModel.Content,
                InformationTypeId = contactInformationModel.InformationTypeId
            };
            await _contactInformationService.AddContactInformationAsync(contactInformation);
            return RedirectToAction("ViewContact", new { contactInformation.ContactId });
        }

        [HttpGet]
        public async Task<IActionResult> EditContactInformation(int contactInformationId)
        {
            var contactInformation = await _contactInformationService.GetContactInformationWithTypeAsync(contactInformationId);
            var contactInformationModel = new ContactInformationEditDto
            {
                UUID = contactInformation.UUID,
                Content = contactInformation.Content,
                ContactId = contactInformation.ContactId,
                ContactName = contactInformation.Contact.Name + " " + contactInformation.Contact.Surname,
                InformationTypeId = contactInformation.InformationTypeId,
                InformationTypes = await _informationTypeService.GetInformationTypesAsync()
            };
            return View(contactInformationModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditContactInformation(ContactInformationEditDto contactInformationModel)
        {
            var contactInformation = await _contactInformationService.GetContactInformationWithTypeAsync(contactInformationModel.UUID);
            contactInformation.Content = contactInformationModel.Content;
            contactInformation.InformationTypeId = contactInformationModel.InformationTypeId;
            await _contactInformationService.UpdateContactInformationAsync(contactInformation);
            return RedirectToAction("ViewContact", new { contactInformation.ContactId });
        }

        public async Task<IActionResult> DeleteContactInformation(int contactInformationId)
        {
            var contactId = (await _contactInformationService.GetContactInformationAsync(contactInformationId)).ContactId;
            await _contactInformationService.DeleteContactInformationAsync(contactInformationId);
            return RedirectToAction("ViewContact", new { contactId });
        }
    }
}

PhoneBook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Phone Book</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css" integrity="sha512-8D+M+7Y6jVsEa7RD6Kv/Z7EImSpNpQllgaEIQAtqHcI0H6F4iZknRj0Nx1DCdB+TwBaS+702BGWYC0Ze2hpExQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Phone Book</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhoneBook" asp-action="ContactIndex">Contacts</a>
                                
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PhoneBook" asp-action="InformationTypeIndex">Information Types</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Phone Book - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js" integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>